---
title: "R Notebook"
output: html_notebook
---
Load pmatrices
```{r}
# Run 7: NEW GH version 2018-03-12. Same taxa as Run 5 and 6, to confirm we are getting the same number of families in a group using the same software version.
pan7 = read.csv("panmatrices/Run7_pangenome_matrix_t0.tab", sep="\t", header=FALSE, stringsAsFactors=FALSE)
pan7 = panpretty(pan7)
pan7_clean = NAcheck(pan7)

# Run 8: Remove CsymA 
pan8 = read.csv("panmatrices/Run8_pangenome_matrix_t0.tab", sep="\t", header=FALSE, stringsAsFactors=FALSE)
pan8 = panpretty(pan8)
pan8_clean = NAcheck(pan8)
```


Load taxalists
```{r}
R5R6R7_taxa = read.table("taxalists/taxlistR5R6R7.tab", header=TRUE, stringsAsFactors=FALSE, fill=TRUE)
R8_taxa = read.table("taxalists/taxlistR8.tab", header=TRUE, stringsAsFactors=FALSE, fill=TRUE)

thaumR7 = R5R6R7_taxa[which(R5R6R7_taxa$Type_Phylum == "thaum"),1]
aigR7 = R5R6R7_taxa[which(R5R6R7_taxa$Type_Phylum == "aig"),1]
taxlistThaumR7 = taxrownums(df=pan7_clean, taxa_yes=thaumR7)
taxlistAigR7 = taxrownums(df=pan7_clean, taxa_yes=aigR7)

thaumR8 = R8_taxa[which(R8_taxa$Type_Phylum == "thaum"),1]
aigR8 = R8_taxa[which(R8_taxa$Type_Phylum == "aig"),1]
taxlistThaumR8 = taxrownums(df=pan8_clean, taxa_yes=thaumR8)
taxlistAigR8 = taxrownums(df=pan8_clean, taxa_yes=aigR8)

```

Get Shared
```{r}

sharedpanR7 = sharedgroups(pan7_clean, taxlistThaumR7$r_yes)
sharedpanR8 = sharedgroups(pan8_clean, taxlistThaumR8$r_yes)

pangenomelistR7 = names(sharedpanR7$yes_atleastone)
pangenomelistR8 = names(sharedpanR8$yes_atleastone)

# list of gene family filenames to run to BLASToise
writeLines(pangenomelistR7, "annotation/R7_pangenome_fnames.txt")
writeLines(pangenomelistR8, "annotation/R8_pangenome_fnames.txt")

```

Load infile from BLASToise
```{r}
R8pananno_pre = read.csv("annotation/R8thaumpan_anno.all", sep="\t", header=FALSE, stringsAsFactors=FALSE, na.strings=c("","NA")) 

annotable = function(df) {
  df[,1] = gsub(".tab", "", df[,1]) # remove '.tab' in OF name
  ocounts = data.frame(table(df$V1)) # occurence counts for all OFs
  odups = ocounts[ocounts$Freq >1,] # OFs with multiple annos
  odups_name = as.character(odups$Var1) # OF dups name
  dupsdf = data.frame()
  for (i in 1:length(odups_name)) {
    subsub = df[which(df$V1 == odups_name[i]),]
    subsub[1,2] = paste(subsub$V2, collapse=",")
    subsub[1,3] = paste(subsub$V3, collapse=",")
    subsub[1,4] = paste(subsub$V4, collapse=",")
    dupsdf = rbind(dupsdf, subsub[1,])
  }
  dups = c()
  for (i in 1:length(odups_name)) {
    dups = c(dups,which(df$V1 == odups_name[i]))
  }
  nodup = df[-dups,]
  pan_anno_merge = rbind(nodup, dupsdf)
  pan_anno_merge = pan_anno_merge[order(pan_anno_merge$V1),]
  return(pan_anno_merge)
}

pancounts = data.frame(matrix(ncol=0,nrow=0), stringsAsFactors=FALSE)
for(i in 1:length(categories)) {
  result = c(as.character(categories[i]), sum(str_detect(thaumtab$V3, categories[i]), na.rm=TRUE))
  pancounts = rbind(pancounts, result, stringsAsFactors=FALSE)
}

R8pananno_post = annotable(R8pananno_pre)
write.table(R8pananno_post, "annotation/R8ThaumAnno.tab", sep="\t", col.names=F, row.names=F, quote=F)

```